services:
 seller:
  git_url: https://github.com/cheveez1337/rsalvatore.git
  git_branch: master
  dockerfile_path: "./Dockerfile"
  build_root: seller
 buyer:
  git_url: https://github.com/cheveez1337/rsalvatore.git
  git_branch: master
  dockerfile_path: "./Dockerfile"
  build_root: buyer
